apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /users(/|$)(.*)
            backend:
              serviceName: users
              servicePort: 8080
          - path: /apartments(/|$)(.*)
            backend:
              serviceName: apartments
              servicePort: 8080
          - path: /images(/|$)(.*)
            backend:
              serviceName: images
              servicePort: 8080
